---
- hosts: localhost
  connection: local
  tasks:
  - name: Create Ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "key-pair"
      instance_type: t3.micro
      security_group: default
      region: ap-south-2
      aws_access_key: "{{ ec2_access_key }}" # From vault as defined
      aws_secret_key: "{{ ec2_secret_key }}" # From vault as defined
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"  
    loop:
      - { image: 'ami-0a9098891d675c629', name: 'Instance-1' }
      - { image: 'ami-0e7938ad51d883574', name: 'Instance-2' }
      - { image: 'ami-0e7938ad51d883574', name: 'Instance-3' }